### ISSUE TITLE
Review config for each mod

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/squirrelpak-mc12#2]
Look at each config file note any changes that need/want to be made in a new issue and tag it with label enhancement and add reference to the issue next to each line

- [x] actuallyadditions.cfg - Changes Made #17
- [x] betteranimalsplus.cfg - Changes #18
- [x] bibliocraft.cfg - Changes #19
- [x] blockcraftery.cfg - Changes #20 
- [x] Building Gadgets.cfg - Change #21
- [x] chisel.cfg - Config #22 
- [x] erebus.cfg - Changes #24
- [x] gravestone.cfg - Changes #23
- [x] refinedstorage.cfg - Changes #25 
- [x] refinedstorageaddons.cfg - Changes #26
- [x] spiceoflife.cfg - Changes #27
- [x] storagedrawers.cfg - Changes #28
- [x] tcomplement.cfg - Changes #29
- [x] tconstruct.cfg - Changes #30
- [x] TComplementModules.cfg - Changes #31
- [x] travelersbackpack.cfg - Changes #32
- [x] morpheus.cfg - Changes #33
- [x] journeymap_server.cfg - Changes #34
- [x] immersiveengineering.cfg - Changes #35
- [x] ftbutilities.cfg - Changes #36
- [x] ftbbackups.cfg - Changes #37
- [x] advRocketry/advancedRocketry.cfg - Changes #38
- [x] AppliedEnergistics2/AppliedEnergistics2.cfg - Changes #39
- [x] aroma1997/aroma1997sdimension.cfg - Changes #41
- [x] aroma1997/ aroma1997sdimension_gen.json - Changes #40
- [x] atomicscience/mods.cfg - Changes #42
- [x] bbm/atomicscience/DustLootTable.cfg - Changes #43
- [x] cofh/world/config.cfg - Changes #44
- [x] Extreme Reactors/Extreme Reactors.cfg - Changes #45
- [x] pneumaticcraft/thirdparty.cfg - Changes #46
- [x] rftools/dimensions.cfg - Changes #47
- [x] rftools/rftools.cfg - Changes #48
 - [x] unidict/IntegrationModule.cfg - Changes #49
 - [x] unidict/ModConfigModule.cfg - Changes #50

**Comment by DocCyblade** [comment]
All config files now have been added to the check list
